# Generated by Django 4.2 on 2023-04-15 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
